/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jobquest;

import static jobquest.Gender.FEMALE;
import static jobquest.Gender.MALE;

/**
 *
 * @author beddoed
 */
public class GenderSelection extends javax.swing.JFrame {

    private Gender genderSelected;
    
    /**
     * Creates new form GenderSelection
     */
    public GenderSelection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        maleJLabel = new javax.swing.JLabel();
        femaleJLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Character Dress");

        maleJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/male.png"))); // NOI18N
        maleJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maleJLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maleJLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maleJLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maleJLabelMousePressed(evt);
            }
        });

        femaleJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fmale.jpg"))); // NOI18N
        femaleJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                femaleJLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                femaleJLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                femaleJLabelMousePressed(evt);
            }
        });

        nextButton.setText("Next ->");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(maleJLabel)
                .addGap(131, 131, 131)
                .addComponent(femaleJLabel)
                .addGap(181, 181, 181))
            .addGroup(layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(nextButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(femaleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(nextButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void femaleJLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleJLabelMousePressed
        genderSelected = FEMALE;
        maleJLabel.setBorder(new javax.swing.border.EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_femaleJLabelMousePressed

    private void maleJLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleJLabelMouseEntered
       maleJLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_maleJLabelMouseEntered

    private void femaleJLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleJLabelMouseEntered
      femaleJLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    }//GEN-LAST:event_femaleJLabelMouseEntered

    private void maleJLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleJLabelMouseExited
       if (genderSelected != MALE) {
          maleJLabel.setBorder(new javax.swing.border.EmptyBorder(0,0,0,0));
       }
    }//GEN-LAST:event_maleJLabelMouseExited

    private void femaleJLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femaleJLabelMouseExited
        if (genderSelected != FEMALE) {
            femaleJLabel.setBorder(new javax.swing.border.EmptyBorder(0,0,0,0));
        }
    }//GEN-LAST:event_femaleJLabelMouseExited

    private void maleJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleJLabelMouseClicked
    }//GEN-LAST:event_maleJLabelMouseClicked

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        navigateToTask1();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void maleJLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maleJLabelMousePressed
        genderSelected = MALE;
        femaleJLabel.setBorder(new javax.swing.border.EmptyBorder(0,0,0,0));
    }//GEN-LAST:event_maleJLabelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenderSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenderSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenderSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenderSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenderSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel femaleJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel maleJLabel;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables

    boolean isMaleChosen() {
        return genderSelected == MALE;
    }

    boolean isFemaleChosen() {
        return genderSelected == FEMALE;
    }

    private void navigateToTask1() {
        Task1 task1 = new Task1(this);
        task1.setBounds(this.getBounds());
        this.setVisible(false);
        task1.setVisible(true);
    }
}
