/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jobquest;

import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author jamesc
 */
public class Task1 extends javax.swing.JFrame {

    private final GenderSelection genderSelection;
  
    Task1(GenderSelection genderSelection) {
        initComponents();
        this.genderSelection = genderSelection;
    }
    
    public GenderSelection getGenderSelection() {
        return genderSelection;
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        task1NextButton = new javax.swing.JButton();
        task1BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Task 1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><center>Dress your chracter in clothes for a job interview, it is important that you select the right clothes for an interview</center></html>");

        task1NextButton.setText("Next ->");
        task1NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task1NextButtonActionPerformed(evt);
            }
        });

        task1BackButton.setText("<- Back");
        task1BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task1BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(task1BackButton)
                .addGap(132, 132, 132)
                .addComponent(task1NextButton)
                .addGap(316, 316, 316))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(task1NextButton)
                    .addComponent(task1BackButton))
                .addGap(118, 118, 118))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void task1NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task1NextButtonActionPerformed
        CharacterDress characterDress = new CharacterDress(this);
        characterDress.setBounds(this.getBounds());
        this.setVisible(false);
        characterDress.setVisible(true);
    }//GEN-LAST:event_task1NextButtonActionPerformed

    private void task1BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task1BackButtonActionPerformed
       this.setVisible(false);
       this.genderSelection.setVisible(true);
       this.genderSelection.setBounds(this.getBounds());
    }//GEN-LAST:event_task1BackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton task1BackButton;
    private javax.swing.JButton task1NextButton;
    // End of variables declaration//GEN-END:variables
}
